export const FETCH_NEWS = 'FETCH_NEWS';
export const FETCH_NEWS_REQUEST = 'FETCH_NEWS_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const FETCH_ARTICLE = 'FETCH_ARTICLE';
export const FETCH_ARTICLE_REQUEST = 'FETCH_ARTICLE_REQUEST';
export const DELETE_ARTICLE = 'DELETE_ARTICLE';
export const EDIT_ARTICLE = 'EDIT_ARTICLE';
export const CREATE_ARTICLE = 'CREATE_ARTICLE';