export const FETCH_NEWS = 'FETCH_NEWS';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const FETCH_ARTICLE = 'FETCH_ARTICLE';
export const UPDATE_ARTICLE = 'UPDATE_ARTICLE';
export const EDIT_ARTICLE = 'EDIT_ARTICLE'